version: "1.0"
stages:
  - "clone"
  - "build"
  - "test"
steps:
  
  clone_init:
    title: Init Clone
    stage: "clone"
    image: codefresh/cli
    shell: bash
    commands:
      - export PRODUCT_NAME="parser"
      - cf_export PRODUCT_NAME="${PRODUCT_NAME}"

  main_clone:
    title: Clone Main Repo
    stage: "clone"
    type: "git-clone"
    repo: "kubevious/${{CF_REPO_NAME}}"
    revision: "${{CF_BRANCH}}"

  prepare_test:
    title: Prepare Test
    stage: test
    image: 'kubevious/node-builder:12'
    working_directory: ${{main_clone}}/src
    commands:
      - npm install
      - npm install --only=dev
    
  run_test:
    title: Test
    stage: test
    image: 'kubevious/node-builder:12'
    working_directory: ${{main_clone}}/src
    commands:
      - pwd
      - ls -la
      - npm test
    